/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DuasIndexRouteImport } from './routes/duas/index'
import { Route as DuasDuaIdRouteImport } from './routes/duas/$duaId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasIndexRoute = DuasIndexRouteImport.update({
  id: '/duas/',
  path: '/duas/',
  getParentRoute: () => rootRouteImport,
} as any)
const DuasDuaIdRoute = DuasDuaIdRouteImport.update({
  id: '/duas/$duaId',
  path: '/duas/$duaId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/duas/$duaId': typeof DuasDuaIdRoute
  '/duas/': typeof DuasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/duas/$duaId': typeof DuasDuaIdRoute
  '/duas': typeof DuasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/duas/$duaId': typeof DuasDuaIdRoute
  '/duas/': typeof DuasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/duas/$duaId' | '/duas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/duas/$duaId' | '/duas'
  id: '__root__' | '/' | '/duas/$duaId' | '/duas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DuasDuaIdRoute: typeof DuasDuaIdRoute
  DuasIndexRoute: typeof DuasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas/': {
      id: '/duas/'
      path: '/duas'
      fullPath: '/duas/'
      preLoaderRoute: typeof DuasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duas/$duaId': {
      id: '/duas/$duaId'
      path: '/duas/$duaId'
      fullPath: '/duas/$duaId'
      preLoaderRoute: typeof DuasDuaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DuasDuaIdRoute: DuasDuaIdRoute,
  DuasIndexRoute: DuasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
